### ISSUE TITLE
正则一句话

### ISSUE THREAD

**Issue by edward32tnt** [netpi/ip2bit#1]
^(((2[0-5][0-5])|(1[0-9][0-9])|([1-9][0-9])|([0-9]))\.){3}((2[0-5][0-5])|(1[0-9][0-9])|([1-9][0-9])|([0-9]))$

**Comment by netpi** [comment]
@edward32tnt  https://github.com/netpi/ip2bit/commit/14fb3ef1abdaf0f6e8c6e35a592066e7fe1ad61f done.
